// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// alcovelp
NumericMatrix alcovelp(List st, NumericMatrix tr);
RcppExport SEXP catlearn_alcovelp(SEXP stSEXP, SEXP trSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< List >::type st(stSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type tr(trSEXP);
    __result = Rcpp::wrap(alcovelp(st, tr));
    return __result;
END_RCPP
}
