# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

slpALCOVE <- function(st, tr, dec = "ER", humble = TRUE, attcon = FALSE, absval = -1, xtdo = FALSE) {
    .Call('catlearn_slpALCOVE', PACKAGE = 'catlearn', st, tr, dec, humble, attcon, absval, xtdo)
}

